name: Diagnostic

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - name: Print Environment Details
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
          echo "NDK path from step output: ${{ steps.setup-ndk.outputs.ndk-path }}"
          echo "-------------------------------------------------"
          echo "PATH: $PATH"
          echo "-------------------------------------------------"
          echo "Listing NDK root directory ($ANDROID_NDK_HOME):"
          ls -l $ANDROID_NDK_HOME
          echo "-------------------------------------------------"
          echo "Listing NDK toolchain bin directory:"
          ls -l $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          echo "-------------------------------------------------"
          echo "Searching for libunwind.a:"
          find $ANDROID_NDK_HOME -name "libunwind.a"
          echo "-------------------------------------------------"
          echo "Searching for crtbegin_dynamic.o:"
          find $ANDROID_NDK_HOME -name "crtbegin_dynamic.o"